config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'likes/new'
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new create show] do
      resources :comments, only: %i[new create]
      resources :likes, only: %i[create]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  after_create :increment_counter
  after_destroy :decrement_counter

  private

  def increment_counter
    post.increment!(:comments_counter)
  end

  def decrement_counter
    post.decrement!(:comments_counter)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user_post

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Commented.'
    else
      render 'new'
    end
  end

  def comment_params
    params.require(:comment).permit(:text)
  end

  def set_user_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<section>
<h1>Write a Comment</h1>
  <%= form_with model: @comments, url: user_post_comments_path, method: :post, local: true, scope: :comment do |form| %>
    <div class = 'form'>
        <%= form.text_area :text %>
        <%= form.submit 'Add a comment' %>
    </div>
  <% end %>
</section>