config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'likes/new'
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new create show] do
      resources :comments, only: %i[new create]
      resources :likes, only: %i[create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  after_create :increment_counter
  after_destroy :decrement_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recents(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  def first
    comments.order(created_at: :asc).limit(1)
  end

  private

  def increment_counter
    author.increment!(:posts_counter)
  end

  def decrement_counter
    author.decrement!(:posts_counter)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(posts: %i[comments likes]).find(params[:user_id].to_i)
    @posts = @user.posts
  end

  def show
    @post = Post.includes(:comments, :likes).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render 'new'
    end
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<section >
  <h1>Posts</h1>
  <div class = "user-item">
    <div class = "user-img-container">
      <img src="<%= @user.photo %>" />
    </div>
    <div class = "user-info">
        <div class = "user-name-container"><h3><%=@user.name %><h3></div>
        <div class = "user-cont-container">Number of posts: <%= @user.posts_counter || 0 %></div>
    </div>
  </div>

  <ul class="posts-list">
  <% @posts.each do |post| %>
    <li class ="post-item-container"> 
    <%= link_to user_post_path(@user.id, post.id) do %>
      <div class="post-item">
        <h4><%= post.title %></h4>
        <% end %>
        <p><%= post.text %></p>
        <div class="post-cont-container">
          <span>Comments: <%= post.comments_counter || 0 %> </span>
          <span> Likes: <%= post.likes_counter || 0 %></span>
        </div>
      </div>   
      <div class="comments">
        <p> <%= 'There is no comment yet' if post.comments.length === 0 %></p>
        <% post.first.each do |comment| %>
          <p><%= comment.user.name %>: <%= comment.text %></p>
        <% end %>
      </div>
    </li>
  <% end %>
  </ul>
  <button>
  <%= link_to user_posts_path(@user.id) do %>
   Pagination
  <% end %>
  </div>

  </div>
</div>

app/views/posts/new.html.erb
<section>
    <h3>Write a new Post</h3>
    <%= form_with model: @posts, url: user_posts_path(current_user), method: :post, local: true, scope: :post do |form| %>
      <div class='form'>
        <%= form.text_field :title, class: 'title', placeholder: 'Post Title' %>
        <%= form.text_area :text, class: 'text', placeholder: 'Your Post', size: "60x10" %>
        <%= form.submit 'Post', class: 'form_btn' %>
      </div>
    <% end %>

</section>

app/views/posts/show.html.erb
<section class='post'>
    <h1>Posts</h1>
    <div class='post-item'>
        <div class='post-show-name'>
            <h3><%= @post.title %><span>  by <%= @post.author.name %></span></h3>
            <div class="post-cont-container">
                <span>Comments: <%= @post.comments_counter || 0 %> </span>
                <span> Likes: <%= @post.likes_counter || 0 %></span>
            </div>
        </div>
        <p><%= @post.text %></p>
        <%= form_with url: "/users/#{@post.author_id}/posts/#{@post.id}/likes" do |form| %>
        <%= form.submit 'Like' %>
      <%end%>
    </div>   
    <div class="comments">
        <p> <%= 'There is no comment yet' if @post.comments.length === 0 %></p>
        <% @post.recents.each do |comment| %>
          <p><%= comment.user.name %> : <%= comment.text %></p>
        <% end %>
    </div>
    <%= link_to new_user_post_comment_path(current_user, @post) do %>
        <div>
        <button>Write a new comment...</button>
        </div>
        <% end %>
</section>